# -*- coding: utf-8 -*-
"""Codecarbon TLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGiZ2ueRr8J2JIVTtS0FNxC8L6iixhYg
"""

!pip install codecarbon

from codecarbon import EmissionsTracker

# Initialize the tracker
tracker = EmissionsTracker()

# Start monitoring energy consumption
tracker.start()

# -*- coding: utf-8 -*-
"""TLP Accessible with CodeCarbon Tracking

Automatically generated by Colab.
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from codecarbon import EmissionsTracker, track_emissions

# Option 1: Tracking a specific function execution using the decorator
@track_emissions(project_name="tlp_plot_rendering")
def render_accessible_tlp(df_top, cvd_mode=True):
    """
    Renders TLP with CVD-friendly colors, texture hatching, and explicit icons.
    """
    fig, ax = plt.subplots(figsize=(8, 4))

    # Select Palette based on Accessibility Settings
    color_risk = '#D55E00' if cvd_mode else '#D9534F'   # Vermillion / Red
    color_safe = '#0072B2' if cvd_mode else '#5CB85C'   # Blue / Green

    bars = []
    for idx, row in df_top.iterrows():
        is_risk = row['shap_contribution'] > 0
        color = color_risk if is_risk else color_safe
        hatch = '///' if is_risk else '...'              # Redundant texture
        icon = "[▲] " if is_risk else "[▼] "             # Redundant symbol

        bar = ax.barh(icon + row['feature'], row['shap_contribution'],
                      color=color, hatch=hatch, edgecolor='black', linewidth=0.8)
        bars.append(bar)

    ax.axvline(0, color='black', linestyle='--', linewidth=1)
    ax.set_xlabel("SHAP Value Contribution (Risk Impact)")
    ax.set_title("Accessible Traffic Light Plot (CVD Mode)")
    plt.tight_layout()
    plt.show()


# Option 2: Wrap the entire execution script using CodeCarbon Context Manager
with EmissionsTracker(project_name="tlp_full_pipeline") as tracker:

    # --- Initial Sample Run ---
    data = {
        'feature': ['Feature A', 'Feature B', 'Feature C', 'Feature D', 'Feature E'],
        'shap_contribution': [0.5, -0.3, 0.7, -0.1, 0.4]
    }
    df_sample = pd.DataFrame(data)

    # Render the plot in CVD mode
    render_accessible_tlp(df_sample, cvd_mode=True)


    # --- Simulated pcI Dataset (Software Defects) ---
    dummy_pci_data = {
        'lines_of_code': np.random.randint(100, 5000, 5),
        'cyclomatic_complexity': np.random.randint(5, 50, 5),
        'developer_experience_months': np.random.randint(6, 120, 5),
        'test_coverage_percentage': np.random.randint(30, 99, 5),
        'number_of_commits': np.random.randint(10, 200, 5)
    }
    df_pci_software_defect = pd.DataFrame(dummy_pci_data)

    # Extract feature names
    realtime_feature_names_pci = df_pci_software_defect.columns.tolist()

    print("Simulated pcI dataset columns (software defect feature names):")
    print(realtime_feature_names_pci)

    new_shap_contributions_pci = [0.7, 0.5, -0.3, 0.6, -0.2]

    if len(realtime_feature_names_pci) != len(new_shap_contributions_pci):
        print(f"Warning: Feature count mismatch. Adjusting.")
        if len(realtime_feature_names_pci) > len(new_shap_contributions_pci):
            new_shap_contributions_pci.extend([0] * (len(realtime_feature_names_pci) - len(new_shap_contributions_pci)))
        else:
            new_shap_contributions_pci = new_shap_contributions_pci[:len(realtime_feature_names_pci)]

    df_sample_pci = pd.DataFrame({
        'feature': realtime_feature_names_pci,
        'shap_contribution': new_shap_contributions_pci
    })

    print("New df_sample with realtime pcI software defect feature names:")
    display(df_sample_pci)

    # Render complete pcI plot
    render_accessible_tlp(df_sample_pci, cvd_mode=True)


    # --- Top 5 Highest Risk Features ---
    df_risk_features = df_sample_pci[df_sample_pci['shap_contribution'] > 0]
    df_top_risk_features = df_risk_features.sort_values(by='shap_contribution', ascending=False).head(5)

    print("Top 5 Highest Risk Features:")
    display(df_top_risk_features)
    render_accessible_tlp(df_top_risk_features, cvd_mode=True)


    # --- Top 5 Lowest Risk Features ---
    df_low_risk_features = df_sample_pci[df_sample_pci['shap_contribution'] < 0]
    df_top_10_low_risk_features = df_low_risk_features.sort_values(by='shap_contribution', ascending=True).head(5)

    print(f"Displaying {len(df_top_10_low_risk_features)} lowest risk features:")
    display(df_top_10_low_risk_features)
    render_accessible_tlp(df_top_10_low_risk_features, cvd_mode=True)


    # --- All Risk Features ---
    df_all_risk_features = df_sample_pci[df_sample_pci['shap_contribution'] > 0]
    print(f"Displaying {len(df_all_risk_features)} all risk features:")
    display(df_all_risk_features)
    render_accessible_tlp(df_all_risk_features, cvd_mode=True)


    # --- All Low Risk Features ---
    df_all_low_risk_features = df_sample_pci[df_sample_pci['shap_contribution'] < 0]
    print(f"Displaying {len(df_all_low_risk_features)} all low risk features:")
    display(df_all_low_risk_features)
    render_accessible_tlp(df_all_low_risk_features, cvd_mode=True)

# Inspection code: View the saved emissions log
emissions_df = pd.read_csv("emissions.csv")
print("\n--- CODECARBON EMISSIONS SUMMARY ---")
display(emissions_df[["project_name", "duration", "emissions", "cpu_energy", "gpu_energy"]])

# -*- coding: utf-8 -*-
"""TLP Accessible with CodeCarbon Tracking

Automatically generated by Colab.
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from codecarbon import EmissionsTracker, track_emissions

# Option 1: Tracking a specific function execution using the decorator
@track_emissions(project_name="tlp_plot_rendering")
def render_accessible_tlp(df_top, cvd_mode=True):
    """
    Renders TLP with CVD-friendly colors, texture hatching, and explicit icons.
    """
    fig, ax = plt.subplots(figsize=(8, 4))

    # Select Palette based on Accessibility Settings
    color_risk = '#D55E00' if cvd_mode else '#D9534F'   # Vermillion / Red
    color_safe = '#0072B2' if cvd_mode else '#5CB85C'   # Blue / Green

    bars = []
    for idx, row in df_top.iterrows():
        is_risk = row['shap_contribution'] > 0
        color = color_risk if is_risk else color_safe
        hatch = '///' if is_risk else '...'              # Redundant texture
        icon = "[▲] " if is_risk else "[▼] "             # Redundant symbol

        bar = ax.barh(icon + row['feature'], row['shap_contribution'],
                      color=color, hatch=hatch, edgecolor='black', linewidth=0.8)
        bars.append(bar)

    ax.axvline(0, color='black', linestyle='--', linewidth=1)
    ax.set_xlabel("SHAP Value Contribution (Risk Impact)")
    ax.set_title("Accessible Traffic Light Plot (CVD Mode)")
    plt.tight_layout()
    plt.show()


# Option 2: Wrap the entire execution script using CodeCarbon Context Manager
with EmissionsTracker(project_name="tlp_full_pipeline") as tracker:

    # --- Initial Sample Run ---
    data = {
        'feature': ['Feature A', 'Feature B', 'Feature C', 'Feature D', 'Feature E'],
        'shap_contribution': [0.5, -0.3, 0.7, -0.1, 0.4]
    }
    df_sample = pd.DataFrame(data)

    # Render the plot in CVD mode
    render_accessible_tlp(df_sample, cvd_mode=True)


    # --- Simulated pcI Dataset (Software Defects) ---
    dummy_pci_data = {
        'lines_of_code': np.random.randint(100, 5000, 5),
        'cyclomatic_complexity': np.random.randint(5, 50, 5),
        'developer_experience_months': np.random.randint(6, 120, 5),
        'test_coverage_percentage': np.random.randint(30, 99, 5),
        'number_of_commits': np.random.randint(10, 200, 5)
    }
    df_pci_software_defect = pd.DataFrame(dummy_pci_data)

    # Extract feature names
    realtime_feature_names_pci = df_pci_software_defect.columns.tolist()

    print("Simulated pcI dataset columns (software defect feature names):")
    print(realtime_feature_names_pci)

    new_shap_contributions_pci = [0.7, 0.5, -0.3, 0.6, -0.2]

    if len(realtime_feature_names_pci) != len(new_shap_contributions_pci):
        print(f"Warning: Feature count mismatch. Adjusting.")
        if len(realtime_feature_names_pci) > len(new_shap_contributions_pci):
            new_shap_contributions_pci.extend([0] * (len(realtime_feature_names_pci) - len(new_shap_contributions_pci)))
        else:
            new_shap_contributions_pci = new_shap_contributions_pci[:len(realtime_feature_names_pci)]

    df_sample_pci = pd.DataFrame({
        'feature': realtime_feature_names_pci,
        'shap_contribution': new_shap_contributions_pci
    })

    print("New df_sample with realtime pcI software defect feature names:")
    display(df_sample_pci)

    # Render complete pcI plot
    render_accessible_tlp(df_sample_pci, cvd_mode=True)


    # --- Top 5 Highest Risk Features ---
    df_risk_features = df_sample_pci[df_sample_pci['shap_contribution'] > 0]
    df_top_risk_features = df_risk_features.sort_values(by='shap_contribution', ascending=False).head(5)

    print("Top 5 Highest Risk Features:")
    display(df_top_risk_features)
    render_accessible_tlp(df_top_risk_features, cvd_mode=True)


    # --- Top 5 Lowest Risk Features ---
    df_low_risk_features = df_sample_pci[df_sample_pci['shap_contribution'] < 0]
    df_top_10_low_risk_features = df_low_risk_features.sort_values(by='shap_contribution', ascending=True).head(5)

    print(f"Displaying {len(df_top_10_low_risk_features)} lowest risk features:")
    display(df_top_10_low_risk_features)
    render_accessible_tlp(df_top_10_low_risk_features, cvd_mode=True)


    # --- All Risk Features ---
    df_all_risk_features = df_sample_pci[df_sample_pci['shap_contribution'] > 0]
    print(f"Displaying {len(df_all_risk_features)} all risk features:")
    display(df_all_risk_features)
    render_accessible_tlp(df_all_risk_features, cvd_mode=True)


    # --- All Low Risk Features ---
    df_all_low_risk_features = df_sample_pci[df_sample_pci['shap_contribution'] < 0]
    print(f"Displaying {len(df_all_low_risk_features)} all low risk features:")
    display(df_all_low_risk_features)
    render_accessible_tlp(df_all_low_risk_features, cvd_mode=True)

# Inspection code: View the saved emissions log
emissions_df = pd.read_csv("emissions.csv")
print("\n--- CODECARBON EMISSIONS SUMMARY ---")
display(emissions_df[["project_name", "duration", "emissions", "cpu_energy", "gpu_energy"]])

mean_emissions = emissions_df['emissions'].mean()
print(f"Mean emissions across all runs: {mean_emissions:.6f} kg CO2eq")

# Calculate average carbon intensity per project
# Carbon intensity = total emissions / total duration for each project

project_avg_emissions_duration = emissions_df.groupby('project_name')[['emissions', 'duration']].mean().reset_index()
project_avg_emissions_duration['carbon_intensity_kg_co2eq_per_second'] = project_avg_emissions_duration['emissions'] / project_avg_emissions_duration['duration']

print("\n--- Average Carbon Intensity per Project (kg CO2eq/second) ---")
display(project_avg_emissions_duration[['project_name', 'carbon_intensity_kg_co2eq_per_second']])

# Calculate total energy consumption by project
project_energy_consumption = emissions_df.groupby('project_name')[['cpu_energy', 'gpu_energy', 'ram_energy']].sum().reset_index()

print("\n--- Total Energy Consumption by Project (kWh) ---")
display(project_energy_consumption)

project_energy_consumption['total_energy'] = project_energy_consumption['cpu_energy'] + project_energy_consumption['gpu_energy'] + project_energy_consumption['ram_energy']
project_energy_consumption['ram_percentage'] = (project_energy_consumption['ram_energy'] / project_energy_consumption['total_energy']) * 100

print("\n--- RAM Energy Percentage by Project ---")
display(project_energy_consumption[['project_name', 'ram_percentage']])

!pip install python-docx

from docx import Document

# Create a new Document
document = Document()
document.add_heading('Emissions Data Report Summary', level=1)

# Add Overall Emissions summary
document.add_heading('1. Overall Emissions', level=2)
document.add_paragraph(f"The mean emissions across all runs was approximately {mean_emissions:.6f} kg CO2eq.")

# Add Project Emissions summary
document.add_heading('2. Project Emissions', level=2)
project_emissions_text = """
Both `tlp_full_pipeline` and `tlp_plot_rendering` projects showed very low total emissions.
Here's a breakdown of total emissions per project:
"""
document.add_paragraph(project_emissions_text)
for index, row in project_emissions.iterrows():
    document.add_paragraph(f"- {row['project_name']}: {row['emissions']:.6f} kg CO2eq", style='List Bullet')

# Add Carbon Intensity summary
document.add_heading('3. Carbon Intensity', level=2)
carbon_intensity_text = "The average carbon intensity for both projects was also very low, indicating efficient processing in terms of carbon footprint."
document.add_paragraph(carbon_intensity_text)
for index, row in project_avg_emissions_duration.iterrows():
    document.add_paragraph(f"- {row['project_name']}: {row['carbon_intensity_kg_co2eq_per_second']:.6f} kg CO2eq/second", style='List Bullet')

# Add Energy Consumption Breakdown summary
document.add_heading('4. Energy Consumption Breakdown', level=2)
energy_breakdown_text = """
The total energy consumption for both projects was minimal. RAM energy accounted for a significant portion of the total energy consumption in both projects.

Energy Consumption by Component per Project:
"""
document.add_paragraph(energy_breakdown_text)
for index, row in project_energy_consumption.iterrows():
    document.add_paragraph(f"- **Project: {row['project_name']}**", style='List Bullet')
    document.add_paragraph(f"  - CPU Energy: {row['cpu_energy']:.6f} kWh", style='List Bullet')
    document.add_paragraph(f"  - GPU Energy: {row['gpu_energy']:.6f} kWh", style='List Bullet')
    document.add_paragraph(f"  - RAM Energy: {row['ram_energy']:.6f} kWh ({row['ram_percentage']:.2f}% of total)", style='List Bullet')

# Save the document
document.save('emissions_report.docx')
print("Emissions report saved to emissions_report.docx")

project_energy_consumption['cpu_percentage'] = (project_energy_consumption['cpu_energy'] / project_energy_consumption['total_energy']) * 100
project_energy_consumption['gpu_percentage'] = (project_energy_consumption['gpu_energy'] / project_energy_consumption['total_energy']) * 100

print("\n--- Energy Consumption Percentage by Hardware Component per Project ---")
display(project_energy_consumption[['project_name', 'cpu_percentage', 'gpu_percentage', 'ram_percentage']])

print("\n--- Detailed Energy Consumption by Hardware Component per Project (kWh) ---")
display(project_energy_consumption[['project_name', 'cpu_energy', 'gpu_energy', 'ram_energy', 'total_energy']])

"""### Comparison of CodeCarbon Results: 'SHAP and TLP Pipeline' vs. 'TLP Plot Rendering'

Based on the `emissions_df`, we can compare the following two projects:

*   **`tlp_full_pipeline`**: This project tracks the emissions for the entire script execution, including the generation of dummy SHAP-like data (`df_sample_pci`) and all subsequent `render_accessible_tlp` function calls within its context manager.
*   **`tlp_plot_rendering`**: This project specifically tracks the emissions generated by each individual call to the `render_accessible_tlp` function, thanks to the `@track_emissions` decorator.

Let's summarize their key metrics:

"""

# Display total emissions for comparison
print("\n--- Total Emissions Comparison (kg CO2eq) ---")
display(project_emissions)

# Display average carbon intensity for comparison
print("\n--- Average Carbon Intensity Comparison (kg CO2eq/second) ---")
display(project_avg_emissions_duration[['project_name', 'carbon_intensity_kg_co2eq_per_second']])

# Display energy consumption breakdown for comparison
print("\n--- Energy Consumption Breakdown Comparison (kWh) ---")
display(project_energy_consumption[['project_name', 'cpu_energy', 'gpu_energy', 'ram_energy', 'total_energy']])

"""#### Observations:

*   **Total Emissions**: The `tlp_full_pipeline` (which includes all steps from data generation to multiple TLP renderings) has a slightly higher total emission than `tlp_plot_rendering` (which aggregates only the emissions from the TLP function calls).
*   **Carbon Intensity**: Both projects show very similar and extremely low carbon intensities (emissions per second), indicating that the computational work involved is very light in terms of CO2 equivalent per unit of time.
*   **Energy Consumption**: Similar to emissions, `tlp_full_pipeline` consumed marginally more CPU and RAM energy, which is expected as it encompasses a broader scope of operations. GPU consumption remains zero for both as no GPU was detected or utilized.
"""

import matplotlib.pyplot as plt

# Prepare data for stacked bar chart
project_energy_consumption_stacked = project_energy_consumption.set_index('project_name')

# Create the stacked bar chart
fig, ax = plt.subplots(figsize=(12, 7))
project_energy_consumption_stacked[['cpu_energy', 'gpu_energy', 'ram_energy']].plot(kind='bar', stacked=True, ax=ax)

plt.title('Stacked Energy Consumption (CPU, GPU, RAM) by Project')
plt.xlabel('Project Name')
plt.ylabel('Total Energy Consumption (kWh)')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Energy Type')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure 'timestamp' column is datetime type for proper plotting
emissions_df['timestamp'] = pd.to_datetime(emissions_df['timestamp'])

plt.figure(figsize=(12, 6))
sns.lineplot(x='timestamp', y='emissions', data=emissions_df)
plt.title('Emissions Over Time')
plt.xlabel('Time')
plt.ylabel('Emissions (kg CO2eq)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Aggregate emissions by project name
project_emissions = emissions_df.groupby('project_name')['emissions'].sum().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='project_name', y='emissions', data=project_emissions, palette='magma')
plt.title('Total Emissions by Project')
plt.xlabel('Project Name')
plt.ylabel('Total Emissions (kg CO2eq)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print("Descriptive statistics for df_sample_pci:")
display(df_sample_pci.describe())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.barplot(x='shap_contribution', y='feature', data=df_sample_pci, palette='viridis')
plt.title('SHAP Contribution for Each Feature in df_sample_pci')
plt.xlabel('SHAP Contribution')
plt.ylabel('Feature')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()